CREATE TYPE user_role   AS ENUM ('ADMIN', 'EXPERT', 'USER');
CREATE TYPE gender_enum AS ENUM ('MALE', 'FEMALE', 'OTHER');
CREATE TYPE goal_enum   AS ENUM ('LOSE_WEIGHT', 'MAINTAIN', 'GAIN_MUSCLE', 'MEDICAL');
CREATE TYPE doc_status  AS ENUM ('DRAFT', 'PENDING', 'APPROVED', 'REJECTED');
CREATE TYPE drug_status AS ENUM ('ALLOWED', 'RESTRICTED', 'BANNED');
CREATE TYPE meal_type   AS ENUM ('BREAKFAST', 'LUNCH', 'DINNER', 'SNACK');
CREATE TYPE plan_status AS ENUM ('ACTIVE', 'COMPLETED', 'REVISED', 'CANCELLED');
CREATE TYPE eval_result AS ENUM ('ACHIEVED', 'NOT_ACHIEVED', 'PARTIAL');
CREATE TYPE job_status  AS ENUM ('QUEUED', 'RUNNING', 'DONE', 'FAILED');