services:
  db:
    image: pgvector/pgvector:pg16
    container_name: nutrismart-db
    environment:
      POSTGRES_DB: nutrismart
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d

  redis:
    image: redis:7-alpine
    container_name: nutrismart-redis
    ports:
      - "6380:6379"

volumes:
  pgdata: